### ISSUE TITLE
No such file or directory: '/home/self6dpp/datasets/BOP_DATASETS/lm/models_scaled_f5k/ape/textured.obj'

### ISSUE THREAD

**Issue by tan-tao11** [THU-DA-6D-Pose-Group/self6dpp#13]
I met an error when training the selff6dpp. 
No such file or directory: '/home/self6dpp/datasets/BOP_DATASETS/lm/models_scaled_f5k/ape/textured.obj'

**Comment by pyni** [comment]
Hi, how did you solve it? I cannot find it as well.

**Comment by tan-tao11** [comment]
The obj file could be downloaded from https://github.com/THU-DA-6D-Pose-Group/Self6D-Diff-Renderer/tree/master/data/lm_models/ape.
















At 2022-11-19 19:21:30, "pyni" ***@***.***> wrote:

Hi, how did you solve it? I cannot find it as well.

**Comment by pyni** [comment]
OK, Thanks a lot!
I will try it later.
