### ISSUE TITLE
No such file or directory:'autodl-tmp/self6dpp/datasets/BOP_DATASETS/lm/image_set/ape_test.txt'

### ISSUE THREAD

**Issue by XiaoHaoPan** [THU-DA-6D-Pose-Group/self6dpp#17]
When I run det/yolov4/train_yolov4.sh configs/yolov4/bop_pbr/yolov4x_640_augCosyAAEGray_ranger_lm_pbr_lm_test.py 0.After it has finished training and the model is saved, an error is generated.I set the TOTAL_EPOCHS=4.

As shown in the image:

![`POIANVVC8}ZGDV45D1 A6O](https://user-images.githubusercontent.com/127167436/233086928-df07d2fb-1cd7-4bba-8595-6879314a6635.png)
![43 AL$JS3RL 2 ~Y{C(X_EY](https://user-images.githubusercontent.com/127167436/233086953-715129c8-3f29-4429-ad4c-186a8c939974.png)

I downloaded the LM dataset that was using the diagram command:

![image](https://user-images.githubusercontent.com/127167436/233087494-22dc610d-2d8f-44fd-b7e4-1ab1082c0686.png)

**Comment by wangg12** [comment]
Please find download link in our README.

**Comment by XiaoHaoPan** [comment]
When I tested the command after training, it showed echo 'does not exist.'. How can this be solved, please？

![image](https://user-images.githubusercontent.com/127167436/233794547-ebcad945-fd15-42a6-b6e6-11b456da6e62.png)

**Comment by XiaoHaoPan** [comment]
det/yolov4/test_yolov4.sh <config_path> <gpu_ids> (other args). What should the third parameter in this command set?
