### ISSUE TITLE
关于6DOF姿态估计

### ISSUE THREAD

**Issue by 1574849739** [THU-DA-6D-Pose-Group/self6dpp#2]
你好 有个问题想请教您一下：
      当我在读论文时了解到6DOF 姿态估计有三种主流的方法，分别是基于关键点correspond 、模板匹配的方法‘投票的方法。但在读2021年新的论文时有许多涉及到直接回归的方法，所以想请教你一下这种直接回归的方法是属于他们其中的一个吗？还是另外的一种方法。
      并且在训练时要知道数据集的哪些信息，比如采用correspond的方法我们可以要知道特征点，选择模板匹配的方法我们要知道每个模板图的6D位姿和摄像机参数。那么直接回归的方法对于训练集通常有哪些要求吗？

**Comment by wangg12** [comment]
直接回归法可以视为一种隐式模板匹配法（基于全局信息），我们这里的直接回归是结合了基于关键点的方法（基于局部信息）。
对于训练集的要求具体参见相关论文。
