### ISSUE TITLE
Augmented issue

### ISSUE THREAD

**Issue by XiaoHaoPan** [THU-DA-6D-Pose-Group/self6dpp#21]
Thanks for the great work, I was wondering how the enhancement here is done? What part of the code is it used in the project?

![image](https://github.com/THU-DA-6D-Pose-Group/self6dpp/assets/127167436/942bc4a5-1c2c-45ea-bf68-d7fc680d0b8c)

**Comment by wangg12** [comment]
https://github.com/THU-DA-6D-Pose-Group/self6dpp/blob/main/core/self6dpp/datasets/data_loader_self.py#L313
