### ISSUE TITLE
Pre-computed detected box from yolov4

### ISSUE THREAD

**Issue by HanzhiC** [THU-DA-6D-Pose-Group/self6dpp#3]
Hi, Thanks for releasing the code :)
I am wondering if you could upload the pre-computed 2d bbox from yolov4 (datasets/BOP_DATASETS/lmo/test/test_bboxes/yolov4x_640_test672_augCosyAAEGray_ranger_lmo_pbr_lmo_bop_test_16e.json).

I was using your old pre-computed box from GDRN (datasets/BOP_DATASETS/lmo/test/test_bboxes/faster_R50_FPN_AugCosyAAE_HalfAnchor_lmo_pbr_lmo_fuse_real_all_8e_test_480x640.json) and the results were slightly worse than the paper. Thought it could be the problem of the detector :)

Thanks!

**Comment by shanice-l** [comment]
Hi, we've uploaded this file, plz refer to the new readme.

**Comment by HanzhiC** [comment]
> Hi, we've uploaded this file, plz refer to the new readme.

Hi, seems the pre-computed detection for trainset is somewhat missing? (filename:         "datasets/BOP_DATASETS/lm/test/init_poses/resnest50d_a6_AugCosyAAEGray_BG05_mlBCE_lm_pbr_100e_so_withYolov4PbrBbox_wDeepimPbrPose_lm_13_train.json",
)
It would be nice if you could upload it as well for reproduction :) Thanks!

**Comment by shanice-l** [comment]
@[HanzhiC](https://github.com/HanzhiC) Sorry, I've re-arranged the files. Please check the [link](https://pan.baidu.com/s/1lfVXryDPVv3ujCQzUETdjg?pwd=8nWC#list/path=%2F) again.

**Comment by HanzhiC** [comment]
thanks for quick response :)

**Comment by OasisYang** [comment]
Hi, thanks for releasing the codes! 
Could you also release the pretrained yolo detector, then we can directly run your method on our own data. Thanks a lot.

**Comment by shanice-l** [comment]
> Hi, thanks for releasing the codes! Could you also release the pretrained yolo detector, then we can directly run your method on our own data. Thanks a lot.

Sry, we don't have the plan to release the pretrained YOLO detector. However, we provided the bounding boxes at [link](https://pan.baidu.com/s/1lfVXryDPVv3ujCQzUETdjg?pwd=8nWC#list/path=%2F), the directory should be looked like `datasets/BOP_DATASETS/$dataset_name/test/test_bboxes/`.
