### ISSUE TITLE
Pretrained deepim model

### ISSUE THREAD

**Issue by zeal-up** [THU-DA-6D-Pose-Group/self6dpp#4]
Hi, appreciate for opening your code! It really helps me a lot. You have released the gdrn and self6dpp model, can you also release the trained deepim model?

**Comment by wangg12** [comment]
I think we've already made the refined poses available. You can train your own deepim model, it should be easy.

**Comment by zeal-up** [comment]
ok, thanks for your reply~ But several config folders exist in configs/deepim, I want to know which is the final configuration.
