### ISSUE TITLE
Question regarding init_poses of DeepIM

### ISSUE THREAD

**Issue by DaoyiG** [THU-DA-6D-Pose-Group/self6dpp#5]
Hi!

Thanks for the amazing project and for releasing the code!

I have a question regarding a specific step of DeepIM during testing. If I understand correctly, during training, the DeepIM is trained on synthetic data, with perturbed ground truth pose as supervision. And during testing on real test data, the init_poses will be loaded to provide both estimated pose and bbox.

So I wonder, how do you acquire the init_poses that are used for test time. From the files in [this](https://github.com/THU-DA-6D-Pose-Group/self6dpp/blob/06909562b0d382c60f012c1c183cfe13db444101/core/deepim/tools/lm/lm_1_prepare_posecnn_init_pose.py), is it correct that the init_pose files are generated by the prediction of PoseCNN from [here?](https://drive.google.com/drive/folders/1dxbEn9NOhlWjiEop3QPjT2wi-FB-N1if)

Thanks!

**Comment by wangg12** [comment]
The init_poses of DeepIM are the test results of PBR trained GDR-Net. We do not rely on PoseCNN.
