### ISSUE TITLE
Slightly worse than the published results

### ISSUE THREAD

**Issue by zeal-up** [THU-DA-6D-Pose-Group/self6dpp#7]
Hi~ thanks for publishing your code. The self-training mechanism is a good inspiration in pose estimation without real annotations. 
I ran your code to reproduce the results on Linemod dataset. However, the final result is slightly worse than the results on paper(just a little bit). I trace the results during the whole training procedure and record the best results. The best results seem to match the results on paper. I wonder if you simply report the final result on the paper or do some other chosen like me. 
Appreciate it if you can give me some advice. Maybe I omitted something.

**Comment by shanice-l** [comment]
Actually, we just record the results from the last epoch.

**Comment by zeal-up** [comment]
@shanice-l Thanks for your reply! Maybe just the environmental differences.
