### ISSUE TITLE
Video performance (fps)

### ISSUE THREAD

**Issue by LukasMahieuArinti** [THU-DA-6D-Pose-Group/self6dpp#8]
Hi, 
Thank you for this interesting paper!
I'd be interested to know whether you've ran any performance tests on video footage to investigate whether the model would be applicable in a real-time scenario?

**Comment by wangg12** [comment]
I haven't run video tests. But I think it should be applicable in real-time as long as you deploy it properly (eg. using onnx/tensorrt/openvino).

**Comment by AnukritiSinghh** [comment]
hey @LukasMahieuArinti did you try on real time?
