### ISSUE TITLE
Question about the V_offset

### ISSUE THREAD

**Issue by rcao-hk** [THU-DA-6D-Pose-Group/self6dpp#9]
Hi,

Could you please specify this value? I cannot find it in the config file.

Best regards,
Rui Cao

**Comment by rcao-hk** [comment]
https://github.com/THU-DA-6D-Pose-Group/self6dpp/blob/f8badb6f2586a3d708102fe74e2cdbe78915cc66/core/self6dpp/engine/self_engine_utils.py#L68

**Comment by wangg12** [comment]
Those codes were not used. Sorry for confusing.
